### PR TITLE
Add new protobuf parameters

### PR DESCRIPTION
**Pull request by dominious1**

### CODE REVIEW

**Comment by baziorek** [comment]
It is implementation of an internship project: https://wiki.hyperledger.org/display/INTERN/Iroha+1%3A+extend+queries+with+optional+arguments

@dominious1 Please add more description and make the PR as draft pull request for now.

**Review by baziorek — CHANGES_REQUESTED** [review]
1. Please change **trans** -> **tx**
2. Remember also to generate python code from proto: https://github.com/hyperledger/iroha-python/blob/main/scripts/compile-proto.py

**Comment by dominious1** [comment]
> 1. Please change **trans** -> **tx**
> 2. Remember also to generate python code from proto: https://github.com/hyperledger/iroha-python/blob/main/scripts/compile-proto.py

**Comment by andprogrammer** [comment]
Please be more specific in the PR's description. You can add few more lines from here
https://wiki.hyperledger.org/display/INTERN/Iroha+1%3A+extend+queries+with+optional+arguments

**Pull request closed without merging**
