### PR TITLE
Add possibility of checking transaction status by hash

### PR DESCRIPTION
**Pull request by baziorek**
I noticed that sometimes statuses are not receiving in timeout, if it happen it is really hard to find out what was reason of the transaction if it is not committed - is it still pending, or it was rejected.
So I've decided that it would be really useful if iroha-python has functionality as `iroha-cli` to check status of transaction.
The functionality is really important for me, because I'm integrating external payment system to transfer tokens to iroha from online-bank-transfer, so I must know if transaction in iroha was COMMITTED, REJECTED, or PENDING to provide proper reaction.

### CODE REVIEW

**Comment by kamilsa** [comment]
@kuvaldini will check functionality and review the code

**Comment by kuvaldini** [comment]
@kamilsa I tested. Works fine.

**Review by kuvaldini — APPROVED** [review]

**Review by stepanLav — APPROVED** [review]

**Comment by stepanLav** [comment]
I'm tested too, looks correct

**Comment by baziorek** [comment]
Thanks for reviewing. I don't have permissions to merge the merge request, so if it is reviewed and looks OK somebody with the permissions needs to merge:).

**Pull request merged**
