### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by satellitex**
# Iroha Python v0.95
Iroha Python v0.95

### Python

Supported Python versions: 3.6 (see `tox.ini`). ( WIP : not tried 2.x )
Multiple Python versions can be installed with your system package manager or with the [pyenv](https://github.com/pyenv/pyenv) tool.
The pyenv itself can also be installed with a system package manager or with the [pyenv-installer](https://github.com/pyenv/pyenv-installer) script.

#### Example installation steps

```sh
# Install pyenv using pyenv-installer
curl -L https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer | bash
# pyenv initialization
export PATH="${HOME}/.pyenv/bin:${PATH}"
eval "$(pyenv init -)"
# Also initialize on startup; if you are using zsh, replace "~/.bashrc" with "~/.zshrc"
echo 'export PATH="${HOME}/.pyenv/bin:${PATH}"' >> ~/.bashrc
echo 'eval "$(pyenv init -)"' >> ~/.bashrc
# Install the most recent Python versions (both 3 and 2)
pyenv install 3.6.0
pyenv install 2.7.13
# Bring both installed versions into the scope: we are testing against both versions
pyenv global 3.6.0 2.7.13
# Only the "tox" package needs to be installed manually
pip install tox
```

### Install
```
$ cd iroha-python
$ pip install -r requirement.txt
$ make all
$ python setup.py install
```

### Example Code
```python
import time
import iroha

iroha.setDebugLog()

# Generate Connection used to connect iroha
connection = iroha.gen_connection(ip="127.0.0.1",port=50051)
#connection = iroha.gen_connection(ip="0.0.0.0",port="10001")
creator = "sioya@sporting.salt"
tx_counter = 0

# Generate Keypairs ( Signatories )
keypairs = []
keypairs.append(iroha.keygen())
keypairs.append(iroha.keygen())


# Generate Creator creating transaction and query
creator = iroha.gen_creator("sinkai@jump.com",keypairs,connection)

# Create Transaction
tx1 = creator.create_tx()

# Add Commmand to tx1
tx1.add_command(
    iroha.CreateAccount(
        account_name = "sinkai",
        domain_id = "jump.com",
        main_pubkey = keypairs[0].public_key,
    )
)

# Sign Transaction
tx1.sign()

# Verify tx1 Transaction
assert(tx1.verify())

# Issue tx1 Transaction
tx1.issue()

# Check tranaction status from iroha
while tx1.check().tx_status == iroha.TxStatus.Value("ON_PROCESS"):
    print("Wait Commit")
    time.sleep(0.1)


# Create Query
query1 = creator.create_query()

# Set Query to query1
query1.set_request(
    iroha.GetAccount(
        account_id = "sinkai@jump.com"
    )
)

# Verify query1 Query
assert(query1.verify())

# Issue query1 Query and Get Response
ret = query1.issue()

# Handling query response
if ret.verify():
    if ret.has_error():
        print( ret.error_response() )
    elif ret.has_account():
        print( ret.account() )
    else:
        assert(False)
else:
    print("unverified")
    assert(False)

```

### test
```
$ tox
```

### CODE REVIEW

**Comment by Warchant** [comment]
*[example/example_iroha_python.py, line 62 at r2](https://reviewable.io:443/reviews/hyperledger/iroha-python/22#-KwKu6orp_e_yEbksLaz:-KwKu6orp_e_yEbksLb-:b-othzt5) ([raw file](https://github.com/hyperledger/iroha-python/blob/338393c5e68b2e8699693ffd30cfa42f709a5d9c/example/example_iroha_python.py#L62)):*
> ```Python
> 
> # Issue query1 Query and Get Response
> ret = query1.issue()
> ```

Again, issue is not the right word. Rename to `send`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hyperledger/iroha-python/22)*

**Comment by Warchant** [comment]
- use pep8 to format code
- do not put in the library code which is "for future versions", this is confusing. You  do not know how it will work in future, nobody knows.
- do not use C library with own bindings. Cryptographic library is very essential part of any blockchain. Any mistake may lead to money loss. It is likely that we will change `ed25519` implementation which is currently in iroha, because it is bad. Use existing bindings for ed25519. Cryptographic algorithm does not depend on the implementation.
- do not create pull requests which are 10k lines long. It took me 2 hours to **briefly** look at the code.  Deep analysis will take days of even more. 
- avoid magic numbers, such as for UINT64_NUMBER. If you need to write `2**64`, write `1 << 64` or `2**64`, not the number itself. It is much more concise and clear.
- do not push to the codebase libraries, which may likely to be changed (the code of ed25519 itself)
- please, use static analyzers, such as `sonar` (we have one at https://sonar.soramitsu.co.jp).
- do not rush with this library. I can definitely say that most of the code from this PR will not be used. We are going to write C++ client library in this+next sprint (2-3 weeks). Then, you may want to write python bindings for that libray. This is the only way.

---

Reviewed 68 of 117 files at r1, 41 of 50 files at r2.
Review status: all files reviewed at latest revision, 18 unresolved discussions.

---

*[docs/iroha.helper.rst, line 1 at r2](https://reviewable.io:443/reviews/hyperledger/iroha-python/22#-KwKsLO2ISwor-u0nWhy:-KwKsLO3JvrtCkgRex-r:b-ysllf2) ([raw file](https://github.com/hyperledger/iroha-python/blob/338393c5e68b2e8699693ffd30cfa42f709a5d9c/docs/iroha.helper.rst#L1)):*
> ```reStructuredText
> iroha\.helper package
> ```

Is this autogenerated file?

---

*[example/example_iroha_python.py, line 29 at r2](https://reviewable.io:443/reviews/hyperledger/iroha-python/22#-KwKtSuZWHex71Eut5xN:-KwKtSu_1ro-8vyVPlfR:b-13goai) ([raw file](https://github.com/hyperledger/iroha-python/blob/338393c5e68b2e8699693ffd30cfa42f709a5d9c/example/example_iroha_python.py#L29)):*
> ```Python
>         account_name = "sinkai",
>         domain_id = "jump.com",
>         main_pubkey = keypairs[0].public_key,
> ```

As far as I know, we don't have the term `main` pubkey. All pubkeys are equal.

---

*[example/example_iroha_python.py, line 40 at r2](https://reviewable.io:443/reviews/hyperledger/iroha-python/22#-KwKth3V9MArENFB6KBL:-KwKth3V9MArENFB6KBM:boyy8bo) ([raw file](https://github.com/hyperledger/iroha-python/blob/338393c5e68b2e8699693ffd30cfa42f709a5d9c/example/example_iroha_python.py#L40)):*
> ```Python
> 
> # Issue tx1 Transaction
> tx1.issue()
> ```

the work `issue` has many meanings. Rename to `send`.

---

*[iroha/creator.py, line 11 at r2](https://reviewable.io:443/reviews/hyperledger/iroha-python/22#-KwKubWDdbBd-C0PGaTV:-KwKubWDdbBd-C0PGaTW:bqy0oqy) ([raw file](https://github.com/hyperledger/iroha-python/blob/338393c5e68b2e8699693ffd30cfa42f709a5d9c/iroha/creator.py#L11)):*
> ```Python
> from iroha.query.query import Query
> 
> class Creator:
> ```

Maybe it is not clear from the classname what is the purpose of this class. Rename to `Account`.

---

*[iroha/helper/ed25519.py, line 6 at r2](https://reviewable.io:443/reviews/hyperledger/iroha-python/22#-KwKyY5_DdKdDkgNu1_0:-KwKyY5_DdKdDkgNu1_1:b310ghj) ([raw file](https://github.com/hyperledger/iroha-python/blob/338393c5e68b2e8699693ffd30cfa42f709a5d9c/iroha/helper/ed25519.py#L6)):*
> ```Python
> 
> me = os.path.abspath(os.path.dirname(__file__))
> libed2559 = cdll.LoadLibrary(os.path.join(me, "../lib/ed25519/lib/libed25519.so"))
> ```

I am not sure if this is good idea to do this. 
1. so -- is only for Linux.
2. if it is compiled on amd64 arch, then I can not use it on i386

Why did you select to use that creepy C library instead of using nice existing python's ed25519?

---

*[iroha/helper/ed25519.py, line 118 at r2](https://reviewable.io:443/reviews/hyperledger/iroha-python/22#-KwL-HTiWE1GD6Dng285:-KwL-HTiWE1GD6Dng286:b-v36mty) ([raw file](https://github.com/hyperledger/iroha-python/blob/338393c5e68b2e8699693ffd30cfa42f709a5d9c/iroha/helper/ed25519.py#L118)):*
> ```Python
> 
> 
> def verify(message, signature, public):
> ```

why do you have 2 same functions: `verify` and `verify_int`? 
It is weird, one receives b64encoded signature, another -- not...

---

*[iroha/helper/random.py, line 4 at r2](https://reviewable.io:443/reviews/hyperledger/iroha-python/22#-KwL0aqAbbwqYSfMO8DH:-KwL0aqAbbwqYSfMO8DI:bsqv2we) ([raw file](https://github.com/hyperledger/iroha-python/blob/338393c5e68b2e8699693ffd30cfa42f709a5d9c/iroha/helper/random.py#L4)):*
> ```Python
> source_str = 'abcdefghijklmnopqrstuvwxyz'
> 
> def uuid(num): #疑似
> ```

don't call this function uuid! 
uuid is standardized https://ja.wikipedia.org/wiki/UUID 

If I see function uuid in the code -- I expect to see standardized uuid, not custom.

---

*[iroha/helper/stateless_validator.py, line 104 at r2](https://reviewable.io:443/reviews/hyperledger/iroha-python/22#-KwL1XPELHlK0vpmcn1L:-KwL1XPELHlK0vpmcn1M:bau602j) ([raw file](https://github.com/hyperledger/iroha-python/blob/338393c5e68b2e8699693ffd30cfa42f709a5d9c/iroha/helper/stateless_validator.py#L104)):*
> ```Python
> def transfer_asset(cmd):
>     logger.info("stateless validate transfer_asset")
>     if verify_asset_id(cmd.asset_id) and verify_account_id(cmd.src_account_id) and verify_account_id(cmd.dest_account_id) and verify_amount(cmd.amount):
> ```

use pep8 formatting please. Code will be much more readable.

Remember that code is written once, but read many times.

---

*[iroha/helper/stateless_validator.py, line 121 at r2](https://reviewable.io:443/reviews/hyperledger/iroha-python/22#-KwL2Mid6apye3BZbi1a:-KwL2Mid6apye3BZbi1b:b-no1yor) ([raw file](https://github.com/hyperledger/iroha-python/blob/338393c5e68b2e8699693ffd30cfa42f709a5d9c/iroha/helper/stateless_validator.py#L121)):*
> # TODO not deceided query signatures
query has one signature.

---

*[iroha/helper/stateless_validator.py, line 143 at r2](https://reviewable.io:443/reviews/hyperledger/iroha-python/22#-KwL2naKZkozblr6Fbdk:-KwL2naKZkozblr6Fbdl:b-fheq6r) ([raw file](https://github.com/hyperledger/iroha-python/blob/338393c5e68b2e8699693ffd30cfa42f709a5d9c/iroha/helper/stateless_validator.py#L143)):*
> Stateless validate Not has field
`logger.error([Stateless validation] undefined type of query)`

---

*[iroha/helper/stateless_validator.py, line 246 at r2](https://reviewable.io:443/reviews/hyperledger/iroha-python/22#-KwL4Dum6P3paNYXE_wk:-KwL4Dum6P3paNYXE_wl:b-ny27fy) ([raw file](https://github.com/hyperledger/iroha-python/blob/338393c5e68b2e8699693ffd30cfa42f709a5d9c/iroha/helper/stateless_validator.py#L246)):*
> ```Python
> 
> def verify_quorum(quorum):
>     if 0 != quorum:
> ```

quorum > 0

---

*[iroha/primitive/amount.py, line 4 at r2](https://reviewable.io:443/reviews/hyperledger/iroha-python/22#-KwL4ai-upZ59f0OPNPz:-KwL4ai-upZ59f0OPNQ-:bnoneet) ([raw file](https://github.com/hyperledger/iroha-python/blob/338393c5e68b2e8699693ffd30cfa42f709a5d9c/iroha/primitive/amount.py#L4)):*
> UINT64_NUMBER = int(18446744073709551616)
What is this number?

Is it `uint64_max`?

---

*[iroha/primitive/signatories.py, line 11 at r2](https://reviewable.io:443/reviews/hyperledger/iroha-python/22#-KwL5ILeD1FH7Hoh8HYA:-KwL5ILfE1NZO8_fQL7s:b-lhxd38) ([raw file](https://github.com/hyperledger/iroha-python/blob/338393c5e68b2e8699693ffd30cfa42f709a5d9c/iroha/primitive/signatories.py#L11)):*
> ```Python
>     def append(self, keypair):
>         logger.debug("Signatories.append")
>         if not [ signatory for signatory in self.signatories if signatory.public_key == keypair.public_key ]:
> ```

follow DRY (do not repeat yourself) principle:

you use  this check twice, why don't make it a separate function?

---

*[iroha/query/response.py, line 2 at r2](https://reviewable.io:443/reviews/hyperledger/iroha-python/22#-KwL5nIrOT1kA49FexqL:-KwL5nIrOT1kA49FexqM:b-xp3ndz) ([raw file](https://github.com/hyperledger/iroha-python/blob/338393c5e68b2e8699693ffd30cfa42f709a5d9c/iroha/query/response.py#L2)):*
> ```Python
> from iroha.helper import logger, crypto
> from iroha.helper.exception import NotErrorResponseException, NotAccountAssetResponseException, NotAccountResponseException, NotSignatoriesResponseExcepiton, NotTransactionsResponseException
> ```

very long line, use pep8 formatting!

---

*[schema/endpoint.proto, line 42 at r2](https://reviewable.io:443/reviews/hyperledger/iroha-python/22#-KwL6A6LgXD_oLrKhWLV:-KwL6A6LgXD_oLrKhWLW:b-6ke44m) ([raw file](https://github.com/hyperledger/iroha-python/blob/338393c5e68b2e8699693ffd30cfa42f709a5d9c/schema/endpoint.proto#L42)):*
> ```protobuf
>     rpc Torii (Transaction) returns (google.protobuf.Empty);
>     rpc Status (TxStatusRequest) returns (ToriiResponse);
>     rpc Flush (FlushRequest) returns (FlushResponse);
> ```

What is Flush?

---

*[tests/query/test_response.py, line 47 at r2](https://reviewable.io:443/reviews/hyperledger/iroha-python/22#-KwKwLrMdTqTGJrBzqs9:-KwKwLrMdTqTGJrBzqsA:b-2k8doy) ([raw file](https://github.com/hyperledger/iroha-python/blob/338393c5e68b2e8699693ffd30cfa42f709a5d9c/tests/query/test_response.py#L47)):*
>  asset_id = "sporting.salt/CupNoodles",
Asset id format is 
`asset_name#domain_name`
`[a-z]{3,96}\#[a-z]{3,96}` (it will be changed, very likely)

---

*[tests/transaction/test_transaction.py, line 54 at r2](https://reviewable.io:443/reviews/hyperledger/iroha-python/22#-KwKx7pxDyBIkPKesxz1:-KwKx7pxDyBIkPKesxz2:bopoy9a) ([raw file](https://github.com/hyperledger/iroha-python/blob/338393c5e68b2e8699693ffd30cfa42f709a5d9c/tests/transaction/test_transaction.py#L54)):*
> ```Python
>         tx.time_stamp()
>         tx.add_key_pair(crypto.create_key_pair())
>         tx.sign()
> ```

Maybe logically it would be better to make something like 
```python3
keypairs = []
keypairs.append(crypto.create_key_pair())
keypairs.append(crypto.create_key_pair())
keypairs.append(crypto.create_key_pair())

tx.sign(keypairs)
```
Private key is used only for signing. When you write `tx.add_key_pair(kp)`, logically it means that you store both keys (public and private) inside tx, which is wrong. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hyperledger/iroha-python/22#-:-KwL7x9AXtW6CAWHorYM:b-vrgldq)*

**Comment by Warchant** [comment]
*[iroha/transaction/transaction.py, line 19 at r2](https://reviewable.io:443/reviews/hyperledger/iroha-python/22#-KwLDQ6huX9sHN-VDm-2:-KwLDQ6huX9sHN-VDm-3:bgij3dm) ([raw file](https://github.com/hyperledger/iroha-python/blob/338393c5e68b2e8699693ffd30cfa42f709a5d9c/iroha/transaction/transaction.py#L19)):*
> ```Python
>             signatures = []
>         )
>         self.signatories = Signatories()
> ```

It is "signatures", not signatories.
Signatures --> you sign something and you get signature
Signatory --> the one who signs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hyperledger/iroha-python/22)*

**Comment by Warchant** [comment]
*[iroha/transaction/transaction.py, line 60 at r2](https://reviewable.io:443/reviews/hyperledger/iroha-python/22#-KwLDjyCMsh4AHV4DFz8:-KwLDjyCMsh4AHV4DFz9:b-6mys93) ([raw file](https://github.com/hyperledger/iroha-python/blob/338393c5e68b2e8699693ffd30cfa42f709a5d9c/iroha/transaction/transaction.py#L60)):*
> ```Python
>         """
>         logger.debug("Transaction.add_key_pair")
>         self.signatories.append(keypair)
> ```

You append whole keypair. Why? Both public and **PRIVATE** key are appended. Never store private keypair anywhere in transaction/query/any object.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hyperledger/iroha-python/22)*

**Comment by motxx** [comment]
```
do not rush with this library. I can definitely say that most of the code from this PR will not be used. We are going to write C++ client library in this+next sprint (2-3 weeks). Then, you may want to write python bindings for that libray. This is the only way.
```
The same may be said of other iroha-sdk library, iroha-ios, iroha-javascript, iroha-android, iroha-scala and iroha-dotnet. Please tell it in public channel of slack and telegram.

**Comment by takemiyamakoto** [comment]
I talked to Kaji about this a few weeks ago, but he seems to think that it was more secure to have a native python library, rather than using the C++ shared library. This is something that should be discussed.

**Comment by neewy** [comment]
Mizuki told me about the message of Bogdan, I would like to clear this up:
we are going to do C++ client library only for model + crypto — that is it. We are not going to write whole Iroha for client 😅

**Comment by Warchant** [comment]
> C++ client library only for model + crypto

Yes. Sorry for confusing you, I meant that we are going to write model objects (Transaction, Query, cryptography for them) and other subprojects will be able to reuse them.

**Comment by takemiyamakoto** [comment]
What is the status of this PR?

**Pull request closed without merging**
