### PR TITLE
cherry-pick new features from develop -> main

### PR DESCRIPTION
**Pull request by baziorek**
1. I've updated `develop` to contain all new features from `main`: https://github.com/hyperledger/iroha-python/pull/83
2. I've updated protobufs to be compatible with iroha 1.4 in `develop` branch: https://github.com/hyperledger/iroha-python/pull/96
3. In the current PR I'm cherry-picking features which are not in `main` but they should be:
    - 2. from above
    - https://github.com/hyperledger/iroha-python/pull/77

### CODE REVIEW

**Comment by baziorek** [comment]
@Pawlak00 Could You please take a look. After merging the PR probably Your changes during the internship would be in next release:)

**Comment by Pawlak00** [comment]
> @Pawlak00 Could You please take a look. After merging the PR probably Your changes during the internship would be in next release:)

I don't see changes from here : https://github.com/Pawlak00/iroha-python/commit/b6d7f421fa51200fe5e006585812d77c2f872a6a in your PR, you should check that. They were mentioned in Issue:
https://github.com/hyperledger/iroha-python/issues/78

**Comment by baziorek** [comment]
> > @Pawlak00 Could You please take a look. After merging the PR probably Your changes during the internship would be in next release:)
> 
> I don't see changes from here : [Pawlak00@b6d7f42](https://github.com/Pawlak00/iroha-python/commit/b6d7f421fa51200fe5e006585812d77c2f872a6a) in your PR, you should check that. They were mentioned in Issue: #78

I've added the changes. Could You please take a look again?

**Comment by Pawlak00** [comment]
> > > @Pawlak00 Could You please take a look. After merging the PR probably Your changes during the internship would be in next release:)
> > 
> > 
> > I don't see changes from here : [Pawlak00@b6d7f42](https://github.com/Pawlak00/iroha-python/commit/b6d7f421fa51200fe5e006585812d77c2f872a6a) in your PR, you should check that. They were mentioned in Issue: #78
> 
> I've added the changes. Could You please take a look again?

done. For me looks good

**Review by iceseer — APPROVED** [review]

**Pull request merged**
